-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: 7539d8bd1a00a3c1bfd34cdb606d3a6372e83469
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: autopep8-wrapper
    -   id: check-yaml
    -   id: debug-statements
    -   id: flake8
    -   id: check-ast
    -   id: check-byte-order-marker
    -   id: check-merge-conflict
    -   id: check-json
    -   id: end-of-file-fixer
    -   id: fix-encoding-pragma
    -   id: requirements-txt-fixer
