
sudo: required

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y sshfs

language: python
python:
    - "2.7"

env:
  - TOXENV=py27

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
    - pip install -U pip
    - pip install -U tox
    - pip install -r requirements_dev.txt


# command to run tests, e.g. python setup.py test
script: tox -e ${TOXENV}
